Digidennis:
  Minify:
    cached: TRUE
    addcssrandom: TRUE

Neos:
  Neos:
    fusion:
      autoInclude:
        'Digidennis.Minify': TRUE
  Fusion:
    defaultContext:
      'Digidennis.Minify': 'Digidennis\Minify\Eel\Resource'
